### ISSUE TITLE
Yaw damper / gear warning

### ISSUE THREAD

**Issue by musurca** [cwburnett/msfs-cj4#1]
The yaw damper doesn't work, and the landing gear warning goes off prematurely. This thread details both problems and also provides fixes:

https://forums.flightsimulator.com/t/citation-cj4-yaw-damper-gear-warning-fixes/272098

(Happy to submit a PR if you don't have time to address these -- thanks for the good work here!)

**Comment by cwburnett** [comment]
@musurca we actually moved this project to a GH org. https://github.com/Working-Title-MSFS-Mods/fspackages
If you wouldn't mind, please log the issue there and also feel free to to a PR - but know we're just about to update main with a massive set of changes, so maybe give it a few hours. ;-)

**Comment by musurca** [comment]
okay, will do -- thanks!
